OAP/Controllers/StudentResumeController.cs
using HelperClasses;
using OAP.Domain;
using OAP.Domain.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OAP.Controllers
{
    public class StudentResumeController : BaseController
    {
        private OAPEntities db = new OAPEntities();
        //
        // GET: /StudentResume/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /StudentResume/Details/5

        public ActionResult Details()
        {
            int userId = GetCurrentUserID();
            UserProfile userProfile = db.UserProfile.Find(userId);
            Student student = userProfile.Student;
            StudentResume studentResume = student.StudentResume.FirstOrDefault();
            StudentResumeViewModel studentResumeViewModel = new StudentResumeViewModel();
            if (studentResume != null)
            {
                studentResumeViewModel = MapperHelper.MapToViewModel(studentResume);
            }
            return View(studentResumeViewModel);
        }

        //
        // GET: /StudentResume/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /StudentResume/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /StudentResume/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /StudentResume/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /StudentResume/Delete/5

        public ActionResult Upload(HttpPostedFileBase file, long ID = 0)
        {
            int userId = GetCurrentUserID();
            UserProfile userProfile = db.UserProfile.Find(userId);
            Student student = userProfile.Student;
            string guidString = Guid.NewGuid().ToString();
            if (!Directory.Exists(Server.MapPath("~/Upload/" + student.ID)))
                Directory.CreateDirectory(Server.MapPath("~/Upload/" + student.ID));


            if (ID == 0)
            {
                StudentResume studentResume = new StudentResume();
                studentResume.Student = student;
                studentResume.ModifiedDate = studentResume.UploadedDate = DateTime.Now;
                if (file != null)
                {
                    string path = Server.MapPath("~/Upload/" + student.ID + "/" + guidString +"."+ file.FileName.Split('.')[1]);
                    file.SaveAs(path);
                    studentResume.FilePath = guidString + "." + file.FileName.Split('.')[1];
                }
                db.StudentResume.Add(studentResume);

            }
            else
            {
                StudentResume studentResume = db.StudentResume.Find(ID);
                studentResume.Student = student;
                studentResume.UploadedDate = DateTime.Now;
                if (file != null)
                {
                    string existingFilePath = Server.MapPath("~/Upload/" + student.ID + "/" + studentResume.FilePath);
                    if (System.IO.File.Exists(existingFilePath))
                    {
                        System.IO.File.Delete(existingFilePath);
                    }
                    string path = Server.MapPath("~/Upload/" + student.ID + "/" + guidString + "." + file.FileName.Split('.')[1]);
                    file.SaveAs(path);
                    studentResume.FilePath = guidString + "." + file.FileName.Split('.')[1];
                }
                db.Entry(studentResume).State = EntityState.Modified;
            }
            db.SaveChanges();
            return RedirectToAction("Details");
        }

        //
        // POST: /StudentResume/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

OAP/Views/StudentResume/Details.cshtml
@model OAP.Domain.ViewModel.StudentResumeViewModel
@{
    ViewBag.Title = "Manage Resume";
    Layout = "~/Views/Shared/_StudentLayout.cshtml";
    string url = Request.Url.GetLeftPart(UriPartial.Authority) + Request.ApplicationPath;
    if (url[url.Length - 1] != '/')
    {
        url = url + "/";
    }
    string filePath =@url+"Upload/"+ Model.StudentID + "/";
}
<div class="row">
    <div class="col-md-12">
        <ul class="breadcrumbs-alt">
            <li>
                <a href="#">Manage Resume</a>
            </li>
        </ul>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <header class="panel-heading">@ViewBag.Title
            </header>
            <div class="panel-body">
                   @if(!string.IsNullOrWhiteSpace(Model.FilePath))
                    {
                <div class="col-lg-6">
                 
                    <div class="adv-table">
                        <table class="display table table-bordered table-striped" aria-describedby="editable-sample_info">
                            <tbody>
                                <tr>
                                    <td>
                                        @Html.LabelFor(m => m.UploadedDate)

                                    </td>
                                    <td>
                                        @Html.DisplayFor(m => m.UploadedDate)

                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        @Html.LabelFor(m => m.ModifiedDate)

                                    </td>
                                    <td>
                                        @Html.DisplayFor(m => m.UploadedDate)

                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                    }
                       
                <div class="col-lg-6">
                    @if (!string.IsNullOrWhiteSpace(Model.FilePath))
                    {
                        string fullurl = @filePath + @Model.FilePath;
                         <div class="col-lg-6">
                        <a href="@fullurl"><button type="button" class="btn btn-primary">Download Resume</button></a>
                             </div>
                    }
                     <button type="button" class="btn btn-success" onclick="OpenResumeUpdateModal()"><i class="fa fa-upload"></i> Update Resume</button>
                </div>
               
            </div>
        </section>
    </div>
</div>
<div class="modal fade" id="uploadModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Update Resume</h4>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Upload", "StudentResume", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", role = "form" }))
                {
                    @Html.HiddenFor(m => m.ID)
                    <div class="form-group">
                        <div class="controls col-lg-offset-2 col-lg-10">

                            <input type="file" name="file" id="file" class="default doc" />

                            <p class="help-block uploadFileSizeError ImageError"></p>

                        </div>
                    </div>
                    <div class="form-group">
                        <div class="controls col-lg-offset-2 col-lg-10">

                            <button type="submit" class="btn btn-warning">Upload</button>
                        </div>
                    </div>
                    
                }

            </div>
            <div class="modal-footer">
                <button data-dismiss="modal" class="btn btn-default" type="button">Close</button>
            </div>
        </div>
    </div>
</div>
@section childScripts{
    <script src="/Scripts/OAP/StudentResume.js"></script>
    <script src="/Scripts/OAP/FileValidator.js"></script>
}