OAP/Controllers/BranchController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OAP.Domain;
using OAP.Domain.ViewModel;
using HelperClasses;
using Newtonsoft.Json;
using OAP.Domain.ViewModel.DataTableViewModel;



namespace OAP.Controllers
{
    [Authorize(Roles = "SuperAdmin, CollegeAdmin, Admin")]
    public class BranchController : BaseController
    {
        private OAPEntities db = new OAPEntities();
        public string pageLimitString = System.Configuration.ConfigurationManager.AppSettings["pageLimit"];

        #region Index

        [Authorize]
        public ActionResult Index()
        {
            //IEnumerable<Branch> branches = db.Branch;
            //List<BranchViewModel> branchViewModelList = MapperHelper.MapToViewModelList(branches,1);
            //return View(branchViewModelList);
            return View();
        }

        public void List()
        {
            string[] columns = { "Name" };
            datatableRequest = new DataTableRequest(Request, columns);

           // IQueryable<Branch> branches = db.Branch;
            IQueryable<Branch> branches = (from b in db.Branch
                                         group b by new
                                         {
                                             b.Name
                                         } into bt
                                         select bt.FirstOrDefault());

            int totalRecords = branches.Count();
            int filteredCount = totalRecords;
            if (!string.IsNullOrWhiteSpace(datatableRequest.SearchString))
            {
                branches = (from q in db.Branch where q.Name.Contains(datatableRequest.SearchString) select q);
                filteredCount = branches.Count();
            }
            branches = branches.OrderBy(x => x.Name);
            if (datatableRequest.ShouldOrder)
            {
                branches = branches.OrderByField(datatableRequest.OrderByColumn, datatableRequest.IsOrderAsccending);
            }
            branches = branches.Skip(datatableRequest.ItemsToSkip).Take(datatableRequest.LengthRequired);
            List<BranchViewModel> branchViewModelList = MapperHelper.MapToViewModelList(branches);
            BranchDataTableViewModel dataTableViewModel = new BranchDataTableViewModel(branchViewModelList, datatableRequest.DrawRequestNumber, totalRecords, filteredCount);

            string result = JsonConvert.SerializeObject(dataTableViewModel);
            Response.Write(result);
        }

        #endregion

        #region Details

        //
        // GET: /Branch/Details/5
        [Authorize]
        public ActionResult Details(long id = 0)
        {
            Branch branch = db.Branch.Find(id);
            if (branch == null)
            {
                return HttpNotFound();
            }
            BranchViewModel branchViewModel = MapperHelper.MapToViewModel(branch);
            return View(branchViewModel);
        }

        #endregion

        #region Create

        [Authorize]
        public ActionResult Create()
        {
            BranchViewModel branchViewModel = new BranchViewModel();
            ViewBag.Years = GetYears(0);
            //branchViewModel.CollegeID = id;
            return View(branchViewModel);
        }

        public List<SelectListItem> GetYears(int selectedYear)
        {
            List<SelectListItem> yearListItem = new List<SelectListItem>();
            for (int i = 1; i < 10; i++)
            {
                SelectListItem selectListItem = new SelectListItem();
                selectListItem.Text = i.ToString();
                selectListItem.Value= i.ToString();
                if (i == selectedYear)
                    selectListItem.Selected = true;
                yearListItem.Add(selectListItem);
            }
            return yearListItem;
        }

        [HttpPost]
        public ActionResult Create(BranchViewModel branchViewModel)
        {
            Branch branch = MapperHelper.MapToDomainObject(db, branchViewModel);
            if (ModelState.IsValid)
            {
                branch.CreatedDate = DateTime.Now;
                branch.CreatedBy = GetCurrentUserID();
                branch.ModifiedDate = DateTime.Now;
                branch.ModifiedBy = GetCurrentUserID();
                db.Branch.Add(branch);
                db.SaveChanges();
                return RedirectToAction("Index");
                //return RedirectToAction("AddDetails", "College", new { id = branchViewModel.CollegeID});
            }
            ViewBag.Years = GetYears(branchViewModel.Years);
            return View(branchViewModel);
        }

        #endregion

        #region Edit

        
        [Authorize]
        public ActionResult Edit(long id = 0)
        {
            Branch branch = db.Branch.Find(id);
            if (branch == null)
            {
                return HttpNotFound();
            }
            BranchViewModel branchViewModel = MapperHelper.MapToViewModel(branch);
            ViewBag.Years = GetYears(branch.Years??0);
            return View(branchViewModel);
        }

        [HttpPost]
        public ActionResult Edit(BranchViewModel branchViewModel)
        {
            Branch branch = db.Branch.Find(branchViewModel.ID);
            branch = MapperHelper.MapToDomainObject(db, branchViewModel, branch);
            if (ModelState.IsValid)
            {
                branch.ModifiedDate = DateTime.Now;
                branch.ModifiedBy = GetCurrentUserID();
                db.Entry(branch).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Years = GetYears(branch.Years??0);
            return View(branchViewModel);
        }

        #endregion

        #region Delete

        [Authorize]
        public ActionResult Delete(long id = 0)
        {
            Branch branch = db.Branch.Find(id);
            if (branch == null)
            {
                return HttpNotFound();
            }
            BranchViewModel branchViewModel = MapperHelper.MapToViewModel(branch);
            return View(branchViewModel);
        }


        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(long id)
        {
            Branch branch = db.Branch.Find(id);
            db.Branch.Remove(branch);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public void DeleteBranches(string branchIDString)
        {
            bool result = true;
            if (!string.IsNullOrEmpty(branchIDString))
            {
                try {
                    List<long> branchIDList = branchIDString.Split(',').Select(long.Parse).ToList();
                    foreach (long branchID in branchIDList )
                    {
                        Branch branch = db.Branch.Find(branchID);

                        db.CollegeBranch.RemoveRange(branch.CollegeBranch);
                        List<Student> studentList = branch.Student.ToList();
                        foreach (Student student in studentList)
                        {
                            student.Branch = null;
                            db.Entry(student).State = EntityState.Modified;
                        }
                        db.Branch.Remove(branch);
                    }

                    db.SaveChanges();
                }
                catch { result = false; }
            }
            else
            { result = false; }
            Response.Write(result);
        }

        #endregion

        #region Reference

        //public ActionResult UpdateTransactionLimit(string sortOrder, int totalPages, int pageNo = 1)
        //{
        //    ViewBag.NameSortParam = String.IsNullOrEmpty(sortOrder) ? sortOrder : "Name_Asc";
        //    ViewBag.NameSortParam = sortOrder == "Name_Asc" ? "Name_Desc" : "Name_Asc";

        //    int pageLimit = Convert.ToInt16(pageLimitString);

        //    IEnumerable<Branch> branches = (from mtl in db.Branch
        //                                    select mtl).OrderBy(x => x.ID).Skip(pageLimit * pageNo).Take(pageLimit);

        //    totalPages = (totalPages == null || totalPages == 0) ? (db.Branch.Count() / pageLimit) - 1 : totalPages;
        //    //ViewBag.TotalPages = totalPages;
        //    //ViewBag.CurrentPageNo = pageNo;

        //    List<Branch> merchantTransactionLimitList = branches.ToList();

        //    int rowNumber = ((pageNo - 1) * 10) + 1;

        //    List<BranchViewModel> branchViewModelList = MapperHelper.MapToViewModelList(branches, rowNumber);

        //    string performSort = ViewBag.NameSortParam;

        //    if (!String.IsNullOrEmpty(sortOrder))
        //    {
        //        switch (performSort)
        //        {
        //            case "Name_Asc":
        //                branchViewModelList = branchViewModelList.OrderBy(x => x.Name).ToList();
        //                break;
        //            case "Name_Desc":
        //                branchViewModelList = branchViewModelList.OrderByDescending(x => x.Name).ToList();
        //                break;
        //        }
        //    }


        //    return View(branchViewModelList);
        //}

        #endregion

        public void GetEndYearRangeByBranch(string branchIDString, string startYearString)
        {
            //long branchID = Convert.ToInt32(branchIDString);
            int startYear = Convert.ToInt32(startYearString);
            //BranchRepository _branchRepository = new BranchRepository();
            //Branch branch = _branchRepository.GetBranchByID(branchID);
            //int branchYear = branch!=null?branch.Years != null ? branch.Years.Value : 0:0;
            int branchYear = 4;
            List<SelectListItem> endYearListItem = GetYearRangeByYear(startYear + branchYear);

OAP/Views/Branch/Create.cshtml
@model OAP.Domain.ViewModel.BranchViewModel
@{
    ViewBag.Title = "Create new Branch";
    if (User.IsInRole("CollegeAdmin"))
    {

    }
    else if (User.IsInRole("SuperAdmin"))
    {
        Layout = "~/Views/Shared/_SuperAdminLayout.cshtml";
    }
}

<div class="row">
    <div class="col-md-12">
        <ul class="breadcrumbs-alt">
            <li>
                <a href="#">Institutes</a>
            </li>
            <li>
                <a  href="/Branch/Index">Branches</a>
            </li>
            <li>
                <a class="current" href="#">Create</a>
            </li>
        </ul>
    </div>
</div>

<section class="panel">
    <header class="panel-heading">
        @ViewBag.Title
    </header>
    <div class="panel-body">
        <div class="position-center">
            @using (Html.BeginForm("Create", "Branch", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                <div class="form-group">
                    @Html.LabelFor(m => m.Name,"Name *", new { @class = "col-lg-2 col-sm-2 control-label" })
                    <div class="col-lg-5">
                        @Html.TextBoxFor(m => m.Name, new { @class = "txt form-control" })
                    </div>
                </div>
                 <div class="form-group">
                    @Html.LabelFor(m => m.Years,"Years *", new { @class = "col-lg-2 col-sm-2 control-label" })
                    <div class="col-lg-5">
                        @Html.DropDownListFor(m => m.Years,new SelectList(ViewBag.Years,"Value","Text"),"Select", new { @class = "txt form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-10">
                        <button type="submit" class="btn btn-info">Save</button>
                        <button type="button" class="btn btn-warning" onclick="window.location='/Branch/Index'">Cancel</button>
                    </div>
                </div>

            }
        </div>
    </div>
</section>
@section childScripts{
}

OAP/Views/Branch/Delete.cshtml
@model OAP.Domain.ViewModel.BranchViewModel
@{
    ViewBag.Title = "Delete";
    if (User.IsInRole("CollegeAdmin"))
    {

    }
    else if (User.IsInRole("SuperAdmin"))
    {
        Layout = "~/Views/Shared/_SuperAdminLayout.cshtml";
    }
}
<div class="row">
    <div class="col-sm-12">
        <section class="panel">
            <header class="panel-heading">
                Delete
            </header>
            <div class="panel-body">
                Are you sure you want to delete this record?
                        <p>@Model.Name</p>
                @using (Html.BeginForm("Delete", "Batch", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    @Html.HiddenFor(m => m.ID)
                    <div class="form-group">
                        <div class="col-lg-offset-2 col-lg-10">
                            <button type="submit" class="btn btn-danger">Delete</button>
                            <button type="button" class="btn btn-danger" onclick="window.location='/Branch/Index'">Cancel</button>
                        </div>
                    </div>
                }
            </div>
        </section>
    </div>
</div>
@section childScripts{
}

OAP/Views/Branch/Details.cshtml
@model OAP.Domain.ViewModel.BranchViewModel

@{
    ViewBag.Title = "Details";
    if (User.IsInRole("CollegeAdmin"))
    {

    }
    else if (User.IsInRole("SuperAdmin"))
    {
        Layout = "~/Views/Shared/_SuperAdminLayout.cshtml";
    }
}

<h2>Details</h2>

<fieldset>
    <legend>Branch</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

OAP/Views/Branch/Edit.cshtml
@model OAP.Domain.ViewModel.BranchViewModel
@{
    ViewBag.Title = "Edit Branch";
    if (User.IsInRole("CollegeAdmin"))
    {

    }
    else if (User.IsInRole("SuperAdmin"))
    {
        Layout = "~/Views/Shared/_SuperAdminLayout.cshtml";
    }
}

<div class="row">
    <div class="col-md-12">
        <ul class="breadcrumbs-alt">
            <li>
                <a href="#">Institutes</a>
            </li>
            <li>
                <a  href="/Branch/Index">Branches</a>
            </li>
            <li>
                <a class="current" href="#">Edit</a>
            </li>
        </ul>
    </div>
</div>
<section class="panel">
    <header class="panel-heading">
        @ViewBag.Title
    </header>
    <div class="panel-body">
        <div class="position-center">
            @using (Html.BeginForm("Edit", "Branch", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                @Html.HiddenFor(m=>m.ID)
                @Html.HiddenFor(m=>m.CollegeID)
                <div class="form-group">
                    @Html.LabelFor(m => m.Name,"Name *", new { @class = "col-lg-2 col-sm-2 control-label" })
                    <div class="col-lg-5">
                        @Html.TextBoxFor(m => m.Name, new { @class = "txt form-control" })
                    </div>
                </div>
                 <div class="form-group">
                    @Html.LabelFor(m => m.Years,"Years *", new { @class = "col-lg-2 col-sm-2 control-label" })
                    <div class="col-lg-5">
                        @Html.DropDownListFor(m => m.Years,new SelectList(ViewBag.Years,"Value","Text",Model.Years),"Select", new { @class = "ddl ddlYears form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-10">
                        <button type="submit" class="btn btn-info">Save</button>
                        <button type="button" class="btn btn-warning" onclick="window.location='/Branch/Index'">Cancel</button>
                    </div>
                </div>

            }
        </div>
    </div>
</section>
@section childScripts{
   <script>
       $(function () {
           $(".ddlYears").val("@Model.Years");
       });
    </script>
}

OAP/Views/Branch/Index.cshtml
@{
    ViewBag.Title = "Branch List";
    if (User.IsInRole("CollegeAdmin"))
    {

    }
    else if (User.IsInRole("SuperAdmin"))
    {
        Layout = "~/Views/Shared/_SuperAdminLayout.cshtml";
    }
}
<div class="row">
    <div class="col-md-12">
        <ul class="breadcrumbs-alt">
            <li>
                <a href="#">Institutes</a>
            </li>
            <li>
                <a class="current" href="/Branch/Index">Branches</a>
            </li>
        </ul>
    </div>
</div>

<section class="panel">
    <header class="panel-heading">
       @ViewBag.Title
    </header>
    <div class="panel-body">
        <div class="adv-table">
            <table class="display table table-bordered table-striped" id="dynamic-table" aria-describedby="editable-sample_info">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th><input type="checkbox" class="chkAll" /></th>
                    </tr>
                </thead>
            </table>
        </div>
        <div style="clear: both;"></div>

        <div class="uploadHolder">
            <button type="button" class="btn btn-success" onclick="window.location.href = '/Branch/Create'"><i class="fa fa-plus"></i> Add New </button>
            <button type="button" class="btn btn-danger" onclick="OpenBranchDeleteModal()"><i class="fa fa-minus"></i> Delete</button>
        </div>
    </div>
</section>


<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Delete Warning</h4>
            </div>
            <div class="modal-body">
                Are you sure you want to delete these records.
            </div>
            <div class="modal-footer">
                <button class="btn btn-danger" onclick="DeleteBranch()" type="button">Delete</button>
                <button data-dismiss="modal" class="btn btn-default" type="button">Close</button>
            </div>
        </div>
    </div>
</div>
@section childScripts{
    <script src="~/Scripts/js/advanced-datatable/js/jquery.dataTables.js"></script>
    <script src="~/Scripts/OAP/Branch.js"></script>
    <script>

        function BindBranchDataTable()
        {
            $(".ckhAll").prop("checked",false);
            $('#dynamic-table').dataTable({
                "destroy":true,
                "processing": true,
                "serverSide": true,
                'ajax': '/Branch/List',
                "pagingType": "full_numbers",
                "columns": [
                { "data": "Name" },
                { "data": "" },
                ],
                "columnDefs": [{
                    "targets": [0],
                    "data": "download_link",
                    "render": function (data, type, full) {
                        return '<a href="Edit/' + full.ID + '">' + data + '</a>';
                    }
                },
                {
                    "targets": [1],
                    "bSortable": false,
                    "data": "download_link",
                    "render": function (data, type, full) {
                        return '<input type="checkbox" class="chkSeperate" value="' + full.ID + '"/>';
                    }
                },
                ]
            });
        }

        $(document).ready(function () {
            BindBranchDataTable();
            $(".chkAll").change(function () {
                if ($(this).prop("checked")) {
                    $(".chkSeperate").prop("checked", true);
                }
                else {
                    $(".chkSeperate").prop("checked", false);
                }
            });
        });

    </script>
}