OAP/Controllers/MemberController.cs
using HelperClasses;
using Newtonsoft.Json;
using OAP.Domain;
using OAP.Domain.ViewModel;
using OAP.Domain.ViewModel.DataTableViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using WebMatrix.WebData;

namespace OAP.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class MemberController : BaseController
    {
        //
        // GET: /Member/

        public ActionResult Index()
        {
            return View();
        }

        string[] columns = { "UserName","EmailID", "OrganizationName" };

        public void List()
        {
            datatableRequest = new DataTableRequest(Request, columns);

            //IQueryable<UserProfile> members = db.webpages_Roles.Where(r => r.RoleName.ToLower() == "admin").SelectMany(x => x.UserProfile);
            IQueryable<UserProfile> members = db.webpages_Roles.Where(r => r.RoleName.ToLower() == "CollegeAdmin").SelectMany(x => x.UserProfile);

            int totalRecords = members.Count();
            int filteredCount = totalRecords;

            if (!string.IsNullOrWhiteSpace(datatableRequest.SearchString))
            {
                //members = (from u in db.webpages_Roles.Where(r => r.RoleName.ToLower() == "admin").SelectMany(x => x.UserProfile) where u.UserName.Contains(datatableRequest.SearchString) select u);
                members = (from u in db.webpages_Roles.Where(r => r.RoleName.ToLower() == "CollegeAdmin").SelectMany(x => x.UserProfile) where u.UserName.Contains(datatableRequest.SearchString) select u);
                filteredCount = members.Count();
            }
            members = members.OrderBy(x => x.UserName);
            if (datatableRequest.ShouldOrder)
            {
                members = members.OrderByField(datatableRequest.OrderByColumn, datatableRequest.IsOrderAsccending);
            }
            members = members.Skip(datatableRequest.ItemsToSkip).Take(datatableRequest.LengthRequired);
            List<MemberViewModel> memberViewModelList = MapperHelper.MapToViewModelList(members);


            MemberDataTableViewModel dataTableViewModel = new MemberDataTableViewModel(memberViewModelList, datatableRequest.DrawRequestNumber, totalRecords, filteredCount);

            string result = JsonConvert.SerializeObject(dataTableViewModel);
            Response.Write(result);
        }


        public ActionResult Edit(int id=0)
        {
            UserProfile userprofile = db.UserProfile.Find(id);
            if(userprofile==null)
            {
                return HttpNotFound();
            }
            MemberViewModel memberViewModel = MapperHelper.MapToViewModel(userprofile);
            return View(memberViewModel);

        }

        [HttpPost]
        public ActionResult Edit(MemberViewModel memberViewModel,HttpPostedFileBase file)
        {
            UserProfile userProfile = db.UserProfile.Find(memberViewModel.ID);
            userProfile.EmailID = memberViewModel.EmailID;
            db.Entry(userProfile).State = EntityState.Modified;
            db.SaveChanges();

            UserOrganisation userOrganisation;
            string fileName;
            if (memberViewModel.UserOrganisationViewModel != null)
            {
                if (memberViewModel.UserOrganisationViewModel.ID == 0)
                {
                    memberViewModel.UserOrganisationViewModel.UserId = memberViewModel.ID;
                    userOrganisation = new UserOrganisation();
                    userOrganisation = MapperHelper.MapToDomainObject(db, memberViewModel.UserOrganisationViewModel);
                    if (file != null)
                    {                                                                           //Image selected
                        string serverPath = Server.MapPath("~/Uploaded/OrganisationLogo");
                        if (!Directory.Exists(serverPath))
                            Directory.CreateDirectory(serverPath);
                        string guidString = Guid.NewGuid().ToString();
                        fileName = guidString + "." + file.FileName.Split('.')[1];
                        file.SaveAs(serverPath + "/" + guidString + "." + file.FileName.Split('.')[1]);
                        userOrganisation.OrgLogo = fileName;
                    }
                    db.UserOrganisation.Add(userOrganisation);
                    db.SaveChanges();
                }
                else
                {
                    userOrganisation = db.UserOrganisation.Find(memberViewModel.UserOrganisationViewModel.ID);
                    userOrganisation = MapperHelper.MapToDomainObject(db, memberViewModel.UserOrganisationViewModel,userOrganisation);
                    if (file != null)
                    {                                                                           //Image selected
                        string serverPath = Server.MapPath("~/Uploaded/OrganisationLogo");
                        if (!Directory.Exists(serverPath))
                            Directory.CreateDirectory(serverPath);
                        string guidString = Guid.NewGuid().ToString();
                        fileName = guidString + "." + file.FileName.Split('.')[1];
                        file.SaveAs(serverPath + "/" + guidString + "." + file.FileName.Split('.')[1]);
                        userOrganisation.OrgLogo = fileName;
                    }
                    db.Entry(userOrganisation).State = EntityState.Modified;
                    db.SaveChanges();
                }
            }

            return RedirectToAction("Index");
        }

        public void Delete(string memberIDString)
        {
            bool result = true;
            try
            {
                if (!string.IsNullOrEmpty(memberIDString))
                {
                    List<long> memberIDList = memberIDString.Split(',').Select(long.Parse).ToList();
                    foreach (long memberID in memberIDList)
                    {
                        var membership = (SimpleMembershipProvider)Membership.Provider;
                        string userName = db.UserProfile.Find(memberID).UserName;
                        membership.DeleteAccount(userName);
                        Roles.RemoveUserFromRoles(userName, Roles.GetRolesForUser(userName));
                        db.UserOrganisation.RemoveRange(db.UserProfile.Find(memberID).UserOrganisation);
                        db.SaveChanges();
                        membership.DeleteUser(userName, true);
                    }
                }
                else
                {
                    result = false;
                }
            }
            catch
            {
                result = false;
            }

            Response.Write(result);
        }

    }
}

OAP/Views/Member/Edit.cshtml
@model OAP.Domain.ViewModel.MemberViewModel
@{
    ViewBag.Title = "Edit Member";
    
}

<div class="row">
    <div class="col-md-12">
        <ul class="breadcrumbs-alt">
            <li>
                <a href="/Member/Index">Member Management</a>
            </li>

            <li>
                <a class="current" >  @ViewBag.Title</a>
            </li>
        </ul>
    </div>
</div>


<section class="panel">
    <header class="panel-heading">
        @ViewBag.Title
    </header>
    <div class="panel-body">

        @using (Html.BeginForm("Edit", "Member", FormMethod.Post, new { @class = "form-horizontal", enctype = "multipart/form-data", role = "form" }))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary("", new { @class = "text-danger" })
            @Html.HiddenFor(m=>m.ID)
            if (Model.UserOrganisationViewModel != null)
            {
                @Html.HiddenFor(m=>m.UserOrganisationViewModel.ID)
                @Html.HiddenFor(m=>m.UserOrganisationViewModel.UserId)
               

                    

             
            }
            <div class="form-group">
                @Html.LabelFor(m => m.UserName, new { @class = "col-md-2 control-label" })
                <div class="col-md-6">
                    @Html.TextBoxFor(m => m.UserName, new { @class = "form-control",@readonly="@readonly" })
                </div>
                
            </div>

           
            <div class="form-group">
                @Html.LabelFor(m => m.EmailID, new { @class = "col-md-2 control-label" })
                <div class="col-md-6">
                    @Html.TextBoxFor(m => m.EmailID, new { @class = "form-control" })
                </div>
            </div>
                <div class="form-group">
   
                    @Html.LabelFor(m => m.UserOrganisationViewModel.OrganisationName, new { @class = "col-md-2 control-label" })
                    <div class="col-md-6">
                        @Html.TextBoxFor(m => m.UserOrganisationViewModel.OrganisationName, new { @class = "form-control" })
                    </div>
                </div>
            
                 <div class="form-group ">
                      <label class="control-label col-md-2">Logo</label>
                                <div class="controls col-md-6">
                                    <div class="fileupload fileupload-new" data-provides="fileupload">
                                                <span class="btn btn-white btn-file">
                                                <span class="fileupload-new"><i class="fa fa-paper-clip"></i> Select file</span>
                                                <span class="fileupload-exists"><i class="fa fa-undo"></i> Change</span>
                                                <input type="file" class="default" name="file"  />
                                                </span>
                                        <span class="fileupload-preview" style="margin-left:5px;"></span>
                                        <a href="#" class="close fileupload-exists" data-dismiss="fileupload" style="float: none; margin-left:5px;"></a>
                                    </div>
                                </div>  

                      <div class="col-md-3">
                         <img src="/Uploaded/OrganisationLogo/@Model.UserOrganisationViewModel.OrgLogo "  height="100"/>
                     </div>
                 </div> 
            
             <div class="form-group">
                    @Html.LabelFor(m => m.UserOrganisationViewModel.OrganisationAddress1, new { @class = "col-md-2 control-label" })
                    <div class="col-md-6">
                        @Html.TextBoxFor(m => m.UserOrganisationViewModel.OrganisationAddress1, new { @class = "form-control" })
                    </div>
                </div>
            
             <div class="form-group">
                    @Html.LabelFor(m => m.UserOrganisationViewModel.OrganisationAddress2, new { @class = "col-md-2 control-label" })
                    <div class="col-md-6">
                        @Html.TextBoxFor(m => m.UserOrganisationViewModel.OrganisationAddress2, new { @class = "form-control" })
                    </div>
                </div>
            
             <div class="form-group">
                    @Html.LabelFor(m => m.UserOrganisationViewModel.ContactNumber1, new { @class = "col-md-2 control-label" })
                    <div class="col-md-6">
                        @Html.TextBoxFor(m => m.UserOrganisationViewModel.ContactNumber1, new { @class = "form-control" })
                    </div>
                </div>
            
             <div class="form-group">
                    @Html.LabelFor(m => m.UserOrganisationViewModel.ContactNumber2, new { @class = "col-md-2 control-label" })
                    <div class="col-md-6">
                        @Html.TextBoxFor(m => m.UserOrganisationViewModel.ContactNumber2, new { @class = "form-control" })
                    </div>
                </div>
            
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" class="btn btn-default" value="Save" />
                     <button type="button" class="btn btn-warning" onclick="window.location='/Member/Index'">Cancel</button>
                </div>
            </div>
        }
        </div>

    </section>




      

        @section childScripts{

        }

OAP/Views/Member/Index.cshtml
@model System.Web.Mvc.JsonResult
@{
    ViewBag.Title = "Member List";
}


<div class="row">
    <div class="col-md-12">
        <ul class="breadcrumbs-alt">
            <li>
                <a href="#">Member Management</a>
            </li>
         
            <li>
                <a class="current" href="/Subject/Index">Member List</a>
            </li>
        </ul>
    </div>
</div>

<section class="panel">
    <header class="panel-heading">
        @ViewBag.Title
    </header>
    <div class="panel-body">
        <div class="adv-table">
            <table class="display table table-bordered table-striped" id="dynamic-table" aria-describedby="editable-sample_info">
                <thead>
                    <tr>
                        <th>User Name</th>
                        <th>Email</th>
                        <th>Organisation Name</th>
                        <th style="width: 50px;">
                            <input type="checkbox" class="chkAll" style="margin-left: 33%;" />
                        </th>
                    </tr>
                </thead>
            </table>
        </div>
        <div style="clear: both;"></div>

        <div class="uploadHolder">
            <button type="button" class="btn btn-success" onclick="window.location.href = '/Account/Register'"><i class="fa fa-plus"></i> Add New </button>
            <button type="button" class="btn btn-danger" onclick="OpenDeleteModal()"><i class="fa fa-minus"></i> Delete</button>
        </div>
    </div>
</section>

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Delete Warning</h4>
            </div>
            <div class="modal-body">
                Are you sure you want to delete these records.

            </div>
            <div class="modal-footer">
                <button class="btn btn-danger" onclick="DeleteMember()" type="button">Delete</button>
                <button data-dismiss="modal" class="btn btn-default" type="button">Close</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="alertModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Alert</h4>
            </div>
            <div class="modal-body alertContent">
            </div>
            <div class="modal-footer">
                <button data-dismiss="modal" class="btn btn-default" type="button">Close</button>
            </div>
        </div>
    </div>
</div>

@section childScripts{
    <script src="~/Scripts/js/advanced-datatable/js/jquery.dataTables.js"></script>
    <script src="~/Scripts/OAP/Member.js"></script>

    <script>

        function BindMemberTable() {
            $('#dynamic-table').dataTable({
                "destroy":true,
                "processing": true,
                "serverSide": true,
                'ajax': '/Member/List',
                "pagingType": "full_numbers",
                "columns": [
                { "data": "UserName" },
                { "data": "EmailID" },
                { "data": "OrganisationName" }
                ],
                "columnDefs": [{
                    "targets": [0],
                    "data": "download_link",
                    "render": function (data, type, full) {
                        return '<a href="Edit/' + full.ID + '">' + data + '</a>';
                    }
                },
                  {
                      "targets": [2],
                      "data": "download_link",
                      "bSortable": false,
                  },
                {
                    "targets": [3],
                    "data": "download_link",
                    "bSortable": false,
                    "render": function (data, type, full) {
                        return '<input type="checkbox" style="margin-left: 33%;" class="chkSeperate" value="' + full.ID + '"/>';
                        //return '<a href="Edit/' + full.ID + '">' + data + '</a>';
                    }
                },

                ]
            });
        }

        $(document).ready(function () {
            BindMemberTable();
        });

    </script>
}