OAP/Controllers/PracticeController.cs
using HelperClasses;
using Newtonsoft.Json;
using OAP.Domain;
using OAP.Domain.ViewModel;
using OAP.Domain.ViewModel.DataTableViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static OAP.Controllers.BaseController;
using static OAP.Domain.ViewModel.DataTableViewModel.QuestionDataTableViewModel;

namespace OAP.Controllers
{
    [Authorize(Roles = "SuperAdmin,CollegeAdmin,Admin,Staff")]
    public class PracticeController : Controller
    {
        private OAPEntities db = new OAPEntities();
        public static string saved = "";
        public DataTableRequest datatableRequest { get; set; }

        //
        // GET: /Practice/

        public ActionResult Index()
        {
            ViewBag.Saved = saved;
            saved = "";
            return View();
        }


        public ActionResult Create()
        {
            //ViewBag.Branches = db.Branch;
            return View();
        }

        [HttpPost]
        public ActionResult Create(PracticeSchoolViewModel practiceSchoolViewModel, string save)
        {
            if (save == "Save")
            {
                PracticeSchool practiceSchool = MapperHelper.MapToDomainObject(practiceSchoolViewModel);
                db.PracticeSchool.Add(practiceSchool);
                db.SaveChanges();
                saved = "Session created successfully!";
                return RedirectToAction("Index");
            }
            else
            {
                return View(practiceSchoolViewModel);
            }
        }

        public void List()
        {
            var practiceSessionList = db.PracticeSchool.ToList();
            int totalRecords = practiceSessionList.Count();
            var practiceSessionViewModelList = new List<PracticeSchoolViewModel>();
            foreach (var ps in practiceSessionList)
            {
                practiceSessionViewModelList.Add(new PracticeSchoolViewModel()
                {
                    ID = ps.ID,
                    IsTechnicalSession = ps.IsTechnicalSession ?? false,
                    SessionName = ps.SessionName,
                    Section1 = ps.Section1,
                    Section2 = ps.Section2,
                    Section3 = ps.Section3,
                    Section4 = ps.Section4
                });
            }
            PracticeSchoolDataTable practiceSchoolDataTable = new PracticeSchoolDataTable(practiceSessionViewModelList, 0, totalRecords, 0);

            string result = JsonConvert.SerializeObject(practiceSchoolDataTable);
            Response.Write(result);
        }

        public ActionResult Edit(int id = 0)
        {
            Session["ID"] = id;
            PracticeSchool practiceSchool = db.PracticeSchool.Find(id);
            if (practiceSchool == null)
            {
                return HttpNotFound();
            }
            PracticeSchoolViewModel practiceSchoolViewModel = new PracticeSchoolViewModel();
            practiceSchoolViewModel.IsTechnicalSession = practiceSchool.IsTechnicalSession ?? false;
            practiceSchoolViewModel.Section1 = practiceSchool.Section1;
            practiceSchoolViewModel.Section2 = practiceSchool.Section2;
            practiceSchoolViewModel.Section3 = practiceSchool.Section3;
            practiceSchoolViewModel.Section4 = practiceSchool.Section4;
            practiceSchoolViewModel.SessionName = practiceSchool.SessionName;
            return View(practiceSchoolViewModel);
        }


        public ActionResult AddLevel(int id = 0)
        {
            //ViewBag.Branches = db.Branch;
            return View();
        }

        [HttpPost]
        public ActionResult AddLevel(PracticeSchoolLevelModel practiceSchoolLevelModel, string save)
        {
            if (save == "Save")
            {
                PracticeSchoolLevel practiceSchoolLevel = new PracticeSchoolLevel();
                practiceSchoolLevel.LevelName = practiceSchoolLevelModel.LevelName;
                practiceSchoolLevel.PracticeSchoolId = practiceSchoolLevelModel.ID;
                db.PracticeSchoolLevel.Add(practiceSchoolLevel);
                db.SaveChanges();
                saved = "Level created successfully!";
                return RedirectToAction("Level/" + practiceSchoolLevelModel.ID);
            }
            else
            {
                return View(practiceSchoolLevelModel);
            }
        }

        public void ListLevel(string id)
        {
            int psId = 0;
            if (!string.IsNullOrEmpty(id))
                psId = Convert.ToInt32(id);
            var practiceSessionLevelList = db.PracticeSchoolLevel.Where(x => x.PracticeSchoolId == psId).ToList();
            int totalRecords = practiceSessionLevelList.Count();
            var practiceLevel = new List<PracticeSchoolLevelModel>();
            foreach (var pl in practiceSessionLevelList)
            {
                practiceLevel.Add(new PracticeSchoolLevelModel()
                {
                    ID = pl.ID,
                    LevelName = pl.LevelName,
                    PracticeSchoolID = pl.PracticeSchoolId,
                });
            }
            PracticeSchoolLevelDataTable practiceSchoolLevelDataTable = new PracticeSchoolLevelDataTable(practiceLevel, 0, totalRecords, 0);

            string result = JsonConvert.SerializeObject(practiceSchoolLevelDataTable);
            Response.Write(result);
        }


        public ActionResult Level(int id = 0)
        {
            ViewBag.PracticeSchoolId = id;
            ViewBag.Saved = saved;
            saved = "";
            return View();
        }


        public ActionResult MapLevelQuestions(string id)
        {
            int levelId = 0;
            if (!string.IsNullOrEmpty(id))
                levelId = Convert.ToInt32(id);
            LevelTechnicalQuestionViewModel levelTechnicalQuestionViewModel = new LevelTechnicalQuestionViewModel();
            levelTechnicalQuestionViewModel.SessionLevelId = levelId;
            IQueryable<Tag> tagsList = db.Tag.GroupBy(x => x.Name).Select(x => x.FirstOrDefault());
            levelTechnicalQuestionViewModel.TagViewModelList = MapperHelper.MapToViewModelList(tagsList.OrderBy(x => x.Name));
            return View(levelTechnicalQuestionViewModel);
        }



        public void GetSelectedQuestions(int id, string tags)
        {
            string[] columns = { "Description" };
            datatableRequest = new DataTableRequest(Request, columns);
            IQueryable<TechnicalQuestion> questions = db.PracticeSchoolLevelQuestion.Where(x => x.PracticeSchoolLevelId == id).Select(x => x.TechnicalQuestion);

            if (!string.IsNullOrWhiteSpace(tags))
            {
                List<long> tagIDList = tags.Split(',').ToList().Select(long.Parse).ToList();
                questions = questions.Where(q => q.PracticeSchoolLevelQuestion.Where(asq => asq.PracticeSchoolLevelId == id).Count() <= 0 && (q.TechnicalQuestionTags.Where(qt => tagIDList.Contains(qt.TagID)).Count() > 0));
            }
            int totalRecords = 0;
            int filteredCount = 0;
            totalRecords = questions.Count();
            filteredCount = totalRecords;

            if (!string.IsNullOrWhiteSpace(datatableRequest.SearchString))
            {
                //questions = (from q in db.TechnicalQuestion where q.Description.Contains(datatableRequest.SearchString) select q);
                questions = questions.Where(q => q.Description.Contains(datatableRequest.SearchString)).Select(x => x);
                filteredCount = questions.Count();
            }

            questions = questions.OrderBy(x => x.Description);
            if (datatableRequest.ShouldOrder)
            {
                questions = questions.OrderByField(datatableRequest.OrderByColumn, datatableRequest.IsOrderAsccending);
            }
            questions = questions.Skip(datatableRequest.ItemsToSkip).Take(datatableRequest.LengthRequired);
            List<TechnicalQuestionViewModel> questionViewModelList = MapperHelper.MapToTechnicalViewModelList(questions);

            TechnicalQuestionDataTableViewModel dataTableViewModel = new TechnicalQuestionDataTableViewModel(questionViewModelList, datatableRequest.DrawRequestNumber, totalRecords, filteredCount);

            string result = JsonConvert.SerializeObject(dataTableViewModel);
            Response.Write(result);
        }


        public void GetAvailableQuestions(int id, string tags)
        {
            string[] columns = { "Description" };
            datatableRequest = new DataTableRequest(Request, columns);
            IQueryable<TechnicalQuestion> questions = (from q in db.TechnicalQuestion
                                                       group q by new
                                                       {
                                                           q.Description
                                                       } into qs
                                                       select qs.FirstOrDefault());
            PracticeSchoolLevel practiceSchoolLevelQuestion = db.PracticeSchoolLevel.Find(id);
            int totalRecords = 0;
            int filteredCount = 0;
            if (practiceSchoolLevelQuestion != null)
            {
                List<TechnicalQuestion> existingQuestions = practiceSchoolLevelQuestion.PracticeSchoolLevelQuestion.Select(x => x.TechnicalQuestion).Distinct().ToList();
                List<int> existingQuestionIDs = existingQuestions.Select(x => x.ID).Distinct().ToList();

                if (!string.IsNullOrWhiteSpace(tags))
                {
                    List<long> tagIDList = tags.Split(',').ToList().Select(long.Parse).ToList();
                    questions = questions.Where(q => q.PracticeSchoolLevelQuestion.Where(asq => asq.PracticeSchoolLevelId == id).Count() <= 0 && (q.TechnicalQuestionTags.Where(qt => tagIDList.Contains(qt.TagID)).Count() > 0));

OAP/Views/Practice/AddLevel.cshtml
@model OAP.Domain.ViewModel.PracticeSchoolLevelModel


@{
    ViewBag.Title = "AddLevel";
    Layout = "~/Views/Shared/_SuperAdminLayout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <ul class="breadcrumbs-alt">
            <li>
                <a href="/Practice/Level">Levels</a>
            </li>
            <li>
                <a class="current" href="#">Add New Level</a>
            </li>
        </ul>
    </div>
</div>

<section class="panel">
    <header class="panel-heading">
        Create New Level
    </header>
    <div class="panel-body">
        <div class="position-center">
            @using (Html.BeginForm("AddLevel", "Practice", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", role = "form" }))
            {
                @Html.ValidationSummary(true)
                <div class="form-group">
                    @Html.LabelFor(m => m.LevelName, "Level Name", new { @class = "col-lg-3 col-sm-3 control-label" })
                    <div class="col-lg-5">
                        @Html.TextBoxFor(m => m.LevelName, new { @class = "txt form-control" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(m => m.LevelDescription, "Level Description", new { @class = "col-lg-3 col-sm-3 control-label" })
                    <div class="col-lg-5">
                        @Html.TextBoxFor(m => m.LevelDescription, new { @class = "txt form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-lg-offset-3 col-lg-10">
                        <button type="submit" class="btn btn-info" name="save" id="submit" value="Save">Save</button>
                        <button type="button" class="btn btn-warning" onclick="window.location='/Practice/Level'">Cancel</button>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

@section childScripts{

}

OAP/Views/Practice/Create.cshtml
@model OAP.Domain.ViewModel.PracticeSchoolViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_SuperAdminLayout.cshtml";
}

@*<h2>Create New Session</h2>*@

<div class="row">
    <div class="col-md-12">
        <ul class="breadcrumbs-alt">
            <li>
                <a href="/Practice/Index">Sessions</a>
            </li>
            <li>
                <a class="current" href="#">Add New Session</a>
            </li>
        </ul>
    </div>
</div>

<section class="panel">
    <header class="panel-heading">
        Create New Session
    </header>
    <div class="panel-body">
        <div class="position-center">
            @using (Html.BeginForm("Create", "Practice", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", role = "form" }))
            {
                @Html.ValidationSummary(true)
                <div class="form-group">
                    @Html.LabelFor(m => m.SessionName, "Session Name", new { @class = "col-lg-3 col-sm-3 control-label" })
                    <div class="col-lg-5">
                        @Html.TextBoxFor(m => m.SessionName, new { @class = "txt form-control" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Section1, "Section 1", new { @class = "col-lg-3 col-sm-3 control-label" })
                    <div class="col-lg-5">
                        @Html.TextBoxFor(m => m.Section1, new { @class = "txt form-control" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Section2, "Section 2", new { @class = "col-lg-3 col-sm-3 control-label" })
                    <div class="col-lg-5">
                        @Html.TextBoxFor(m => m.Section2, new { @class = "txt form-control" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Section3, "Section 3", new { @class = "col-lg-3 col-sm-3 control-label" })
                    <div class="col-lg-5">
                        @Html.TextBoxFor(m => m.Section3, new { @class = "txt form-control" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Section4, "Section 4", new { @class = "col-lg-3 col-sm-3 control-label" })
                    <div class="col-lg-5">
                        @Html.TextBoxFor(m => m.Section4, new { @class = "txt form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-lg-12">
                        @Html.LabelFor(m => m.IsTechnicalSession, "Technical", new { @class = "col-lg-3 col-sm-3 control-label" })
                        @Html.RadioButtonFor(m => m.IsTechnicalSession, true,new {@class="col-sm-2"})

                        @Html.LabelFor(m => m.IsTechnicalSession, "Non-Technical", new { @class = "col-lg-3 col-sm-3 control-label" })
                        @Html.RadioButtonFor(m => m.IsTechnicalSession, false, new { @class = "col-sm-2" })
                    </div>

                </div>

                <div class="form-group">
                    <div class="col-lg-offset-3 col-lg-10">
                        <button type="submit" class="btn btn-info" name="save" id="submit" value="Save">Save</button>
                        <button type="button" class="btn btn-warning" onclick="window.location='/Practice/Index'">Cancel</button>
                    </div>
                </div>
            }
        </div>
    </div>
</section>
<div class="modal fade" id="AlertModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Alert</h4>
            </div>
            <div id="column3" style="padding-left: 20px;" class="alertDetailContainer">
            </div>
            <div class="modal-footer">
                <button data-dismiss="modal" class="btn btn-danger btnCloseAlert" type="button">Close</button>
            </div>
        </div>
    </div>
</div>
@section childScripts{
}

OAP/Views/Practice/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_SuperAdminLayout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <ul class="breadcrumbs-alt">
            <li>
                <a class="current" href="#">Practice School</a>
            </li>
        </ul>
    </div>
</div>

<section class="panel">
    <header class="panel-heading">
        Session List
    </header>
    <div class="panel-body">
        <div style="clear: both;"></div>
        <div class="adv-table">
            <table class="display table table-bordered table-striped" id="dynamic-table" aria-describedby="editable-sample_info">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Add Levels</th>
                    </tr>
                </thead>
            </table>
        </div>
        <div style="clear: both;"></div>

        <div class="uploadHolder">
            <button type="button" class="btn btn-success" onclick="window.location.href = '/Practice/Create'"><i class="fa fa-plus"></i>Add Session </button>
        </div>
    </div>
</section>



<div class="modal fade" id="AlertModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Success</h4>
            </div>
            <div id="column" style="padding-left: 20px;" class="alertDetailContainer">
            </div>
            <div class="modal-footer">
                <button data-dismiss="modal" class="btn btn-danger btnCloseAlert" type="button">OK</button>
            </div>
        </div>
    </div>
</div>

@section childScripts{
    <script src="~/Scripts/js/advanced-datatable/js/jquery.dataTables.js"></script>
    <script>
        var popup = '@ViewBag.Saved';


        function BindSessionDataTable() {
            $(".chkAll").prop("checked", false);
            $('#dynamic-table').dataTable({
                "destroy": true,
                "processing": true,
                "serverSide": true,
                'ajax': '/Practice/List',
                "pagingType": "full_numbers",
                "columns": [
                    {
                        "data": "SessionName",
                    },
                ],
                "columnDefs": [{
                    "targets": [0],
                    "data": "download_link",
                    "render": function (data, type, full) {
                        return '<a href="Edit/' + full.ID + '">' + data + '</a>';
                    }
                },
                    {
                        "targets": [1],
                        //"data": "download_link",
                        "bSortable": false,
                        "render": function (data, type, full) {
                            if (full.IsTechnicalSession)
                                return '<a href="Level/' + full.ID + '">' + "Add Levels" + '</a>';
                        }
                    }
                ]
            });
        }

        function OpenAlertModal(message) {
            $("#AlertModal").modal({
                show: true,
            });
            $(".alertDetailContainer").html('');
            $(".alertDetailContainer").html(message);
        }

        $(document).ready(function () {
            BindSessionDataTable();
            if (popup != "") {
                OpenAlertModal(popup);
            }
        });
    </script>
}

OAP/Views/Practice/Level.cshtml
@{
    ViewBag.Title = "Level";
    Layout = "~/Views/Shared/_SuperAdminLayout.cshtml";
}

<div class="row">
    <div class="col-md-12">
        <ul class="breadcrumbs-alt">
            <li>
                <a href="/Practice/Index">Practice School</a>
            </li>
            <li>
                <a class="current" href="#">Levels</a>
            </li>
        </ul>
    </div>
</div>

<section class="panel">
    <header class="panel-heading">
        Level List
    </header>
    <div class="panel-body">
        <div style="clear: both;"></div>
        <div class="adv-table">
            <table class="display table table-bordered table-striped" id="dynamic-table" aria-describedby="editable-sample_info">
                <thead>
                    <tr>
                        <th>Level Name</th>
                        <th>Add Questions</th>
                    </tr>
                </thead>
            </table>
        </div>
        <div style="clear: both;"></div>

        <div class="uploadHolder">
            <button type="button" class="btn btn-success" onclick="window.location.href = '/Practice/AddLevel/'+@ViewBag.PracticeSchoolId"><i class="fa fa-plus"></i>Add Levels </button>
        </div>
    </div>
</section>



<div class="modal fade" id="AlertModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Success</h4>
            </div>
            <div id="column" style="padding-left: 20px;" class="alertDetailContainer">
            </div>
            <div class="modal-footer">
                <button data-dismiss="modal" class="btn btn-danger btnCloseAlert" type="button">OK</button>
            </div>
        </div>
    </div>
</div>

@section childScripts{
    <script src="~/Scripts/js/advanced-datatable/js/jquery.dataTables.js"></script>
    <script>
        var popup = '@ViewBag.Saved';
        var id = '@ViewBag.PracticeSchoolId';

        function BindLevelDataTable() {
            $(".chkAll").prop("checked", false);
            $('#dynamic-table').dataTable({
                "destroy": true,
                "processing": true,
                "serverSide": true,
                'ajax': '/Practice/ListLevel/'+id,
                "pagingType": "full_numbers",
                "columns": [
                    {
                        "data": "LevelName",
                    },
                ],
                "columnDefs": [{
                    "targets": [0],
                    "data": "download_link",
                    "render": function (data, type, full) {
                        return '<a href="Edit/' + full.ID + '">' + data + '</a>';
                    }
                },
                    {
                        "targets": [1],
                        //"data": "download_link",
                        "bSortable": false,
                        "render": function (data, type, full) {
                            return '<a href="/Practice/MapLevelQuestions/' + full.ID + '">' + "Map Questions" + '</a>';
                        }
                    }
                ]
            });
        }

        function OpenAlertModal(message) {
            $("#AlertModal").modal({
                show: true,
            });
            $(".alertDetailContainer").html('');
            $(".alertDetailContainer").html(message);
        }

        $(document).ready(function () {
            BindLevelDataTable();
            if (popup != "") {
                OpenAlertModal(popup);
            }
        });
    </script>
}